// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7e_sVKSwHOfBLo2AW9F15I9BprkaZiVY',
    appId: '1:906367067009:web:2a3fb75df60e1bff757e80',
    messagingSenderId: '906367067009',
    projectId: 'functest-f4a98',
    authDomain: 'functest-f4a98.firebaseapp.com',
    storageBucket: 'functest-f4a98.appspot.com',
    measurementId: 'G-RYHJ8VYC6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWpFGy8SM8YU73gDrUi3iPxdO1RMe-dVQ',
    appId: '1:906367067009:android:ca08e47b8a803762757e80',
    messagingSenderId: '906367067009',
    projectId: 'functest-f4a98',
    storageBucket: 'functest-f4a98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2_Yt82SmlgTBAEwsS2LClajiBXS8f11I',
    appId: '1:906367067009:ios:cb738dd8737e751b757e80',
    messagingSenderId: '906367067009',
    projectId: 'functest-f4a98',
    storageBucket: 'functest-f4a98.appspot.com',
    iosClientId: '906367067009-rqvct7gbdfnpr8u413f41gdh48sd3ebg.apps.googleusercontent.com',
    iosBundleId: 'com.example.myartist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2_Yt82SmlgTBAEwsS2LClajiBXS8f11I',
    appId: '1:906367067009:ios:cb738dd8737e751b757e80',
    messagingSenderId: '906367067009',
    projectId: 'functest-f4a98',
    storageBucket: 'functest-f4a98.appspot.com',
    iosClientId: '906367067009-rqvct7gbdfnpr8u413f41gdh48sd3ebg.apps.googleusercontent.com',
    iosBundleId: 'com.example.myartist',
  );
}
